import Head from 'next/head'
import styles from '../styles/home.module.css'
import Link from 'next/link';

import NavigationBar from '../components/navigation-bar/navigation-bar';
import Footer from '../components/footer/footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>foodkoala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar></NavigationBar>

      <main className={styles.main}>
        <h1 className="title">
          We deliver slowly but at least we're cute!
        </h1>

        <div className={styles.grid}>
          <Link href="/restaurant">
            <a className={styles.card}>
              <h2>Restaurants &rarr;</h2>
              <p>Find the best restaurants in Davao.</p>
            </a>
          </Link>
          

          <a href="#" className={styles.card}>
            <h2>Shops &rarr;</h2>
            <p>Shop online and have them delivered at your doorstep.</p>
          </a>
        </div>
      </main>

      <Footer></Footer>
    </div>
  )
}
