import Head from 'next/head'
import styles from '../styles/home.module.css'
import RestaurantCard from '../components/restaurant/restaurant-card/restaurant-card';

import NavigationBar from '../components/navigation-bar/navigation-bar';
import Footer from '../components/footer/footer';

export default function Restaurant() {
  return (
    <div className={styles.container}>
      <Head>
        <title>foodkoala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar></NavigationBar>

      <main className={styles.mainContent}>
        <h1 className="title">
          Restaurants
        </h1>

        <div>
          <RestaurantCard
            name="The Fat Cow"
            image="https://i0.wp.com/stage.thefatcowgroup.com/wp-content/uploads/2021/09/6-1.png?w=800&ssl=1"
            description="8-hour Spaghetti Bolognese, Black Truffle Pasta, Callos in Chorizo and Garlic">
          </RestaurantCard>

          <RestaurantCard
            name="Rekado Davao"
            image="https://farm5.staticflickr.com/4388/35678253654_99bcf5a032.jpg"
            description="For the Kadayawan menu, we are bringing in the classic Filipino dishes">
          </RestaurantCard>
        </div>
      </main>

      <Footer></Footer>
    </div>
  )
}
